spring:
  jpa:
    properties:
      show-sql: true
  liquibase:
    enabled: true

server:
  port: ${PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: JP IMMERSION HUB
    server: http://localhost:${server.port}/api/v1
    title: Japanese Immersion Hub
    version: 1.0.0
