spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate.dialect: ${DIALECT}
      show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: JP IMMERSION HUB
    server: http://localhost:${server.port}/api/v1
    title: Japanese Immersion Hub
    version: 1.0.0
