spring:
  application:
    name: japanese-immersion-hub

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    driver-class-name: ${DRIVER_NAME}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: ${PORT}
