spring:
  profiles:
    active: dev
  
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: ${PORT}
  servlet:
    context-path: /api/v1
jwt:
  signerKey: ${JWT_SECRET}

oauth2:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  grantType: ${GRANT_TYPE}
  redirectUri: ${REDIRECT_URI}
