spring:
  application:
    name: japanese-immersion-hub
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DRIVER_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate.dialect: ${DIALECT}
      show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: @spring.profiles.active@
server:
  port: ${PORT}
  servlet:
    context-path: /api/v1